name: Build Examples

on:
  workflow_call:

jobs:
  build-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          - basic
          - i2c
        idf_ver:
          - release-v5.1
          - release-v5.2
          - release-v5.3
        idf_target:
          - esp32

    steps:
      - uses: actions/checkout@v4
        with:
          path: rc522
          
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: rc522/examples/${{ matrix.example }}
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
