name: clang-format Check

on:
  pull_request:

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - include
          - src

    steps:
      - uses: actions/checkout@v4
      - name: 'clang-format check'
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 18
          check-path: ${{ matrix.path }}
