name: Check Formatting

on:
  pull_request_target:

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'clang-format check'
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 18
