name: Validate Pull Request

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Check formatting"
        uses: './.github/workflows/clang_format_check.yaml'

      - name: "Build examples"
        uses: './.github/workflows/build_examples.yaml'
