name: Validate PR

on:
  pull_request:

jobs:
  format_check:
    name: "Check formatting"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'clang-format check'
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 18

  build_examples:
    name: "Build examples"
    runs-on: ubuntu-latest

    needs:
      - format_check

    strategy:
      matrix:
        example:
          - basic
          - i2c
        idf_ver:
          - release-v5.0
          - release-v5.1
          - release-v5.2
          - release-v5.3
        idf_target:
          - esp32

    steps:
      - uses: actions/checkout@v4
        with:
          path: rc522
          
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: rc522/examples/${{ matrix.example }}
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
